FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y \
	gcc \
	libpq -dev \
	&& rm -rf /var/lib/apt/ lists /*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/anime_service/ ./src/anime_service/
EXPOSE 8001
CMD [" uvicorn", "src.anime_service.crud_service:app", "--host", "0.0.0.0" , "--port", "8001"]