FROM python:3.11-slim
WORKDIR /app
COPY ./src/frontend/requirements_frontend_service.txt .
RUN pip install --no-cache-dir -r requirements_frontend_service.txt
COPY src/frontend/ ./src/frontend/
EXPOSE 8000
CMD ["uvicorn", "src.frontend.frontend:app", "--host", "0.0.0.0" , "--port","8000"]
